# This file is part of Sherpa Federated Learning Framework.
#
# Sherpa Federated Learning Framework is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation version 3.
#
# Sherpa Federated Learning Framework is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Foobar.  If not, see <https://www.gnu.org/licenses/>.

site_name: Sherpa.ai Federated Learning Framework
docs_dir: sources
extra_css:
  - stylesheets/fonts.css
  - stylesheets/sherpa.css
theme:
  name: "material"
plugins:
  - search
  - mkdocstrings
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - js/sherpa.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
nav:
  - Home: index.md
  - Getting started: getting_started.md
  - Private:
      - Overview: private/overview.md
      - DataNode: private/data_node.md
      - Data: private/data.md
      - Federated Operation: private/federated_operation.md
      - Federated Attack: private/federated_attack.md
      - Reproducibility: private/reproducibility.md
  - Databases: databases.md
  - Data Distribution: data_distribution.md
  - Model:
      - Overview: model.md
      - Supervised Learning: model/supervised.md
      - Unsupervised Learning: model/unsupervised.md
      - Recommender Systems: model/recommender.md
  - Federated Aggregator: federated_aggregator.md
  - Federated Government: federated_government.md
  - Differential Privacy:
      - Overview: differential_privacy/overview.md
      - Mechanisms: differential_privacy/mechanisms.md
      - Sensitivity Sampler: differential_privacy/sensitivity_sampler.md
      - Norm: differential_privacy/norm.md
      - Probability Distribution: differential_privacy/probability_distribution.md
      - Composition: differential_privacy/composition.md
      - Sampling: differential_privacy/sampling.md
